name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Primeiro Hello World no GitHub Actions!
