 name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:    
      - name: Step 1
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'luizrmr'
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
          
        
